default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: genz_backend_app_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: genz_backend_app_test
  host: localhost
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>